import java.io.*;
import java.awt.*;

public class BalancePage extends javax.swing.JFrame {
    
    public static String username = "";
    
    public BalancePage() {
        initComponents();
        try {
            BufferedReader reader = new BufferedReader(new FileReader("src\\AuthenticatedUser.txt"));
            username = reader.readLine();
            String[] response = Balance.getBalance(username);
            welcomeText.setText("Welcome " + username);
            if (response[0].equals("true")) {
                double withdraw = Double.parseDouble(response[2]);
                double deposit = Double.parseDouble(response[3]);
                double budget = Double.parseDouble(response[4]);
                double budgetLeft = budget - withdraw + deposit;
                currentBalance.setText("Current Balance: $" + response[1]);
                totalWithdraw.setText("Total Withdrawn: $" + response[2]);
                totalDeposit.setText("Total Deposit: $" + response[3]);
                totalBudget.setText("Remaining Budget: $" + budgetLeft + "");
            }
            reader.close();
        } catch (Exception e) {
            System.out.println("Error getting User Authentication.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        withdrawPageButton = new javax.swing.JButton();
        depositPageButton = new javax.swing.JButton();
        currentBalance = new javax.swing.JLabel();
        totalWithdraw = new javax.swing.JLabel();
        totalBudget = new javax.swing.JLabel();
        totalDeposit = new javax.swing.JLabel();
        newBudget = new javax.swing.JTextField();
        setBudget = new javax.swing.JButton();
        errorField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));

        welcomeText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        welcomeText.setText("Welcome ......................");

        homeButton.setBackground(new java.awt.Color(0, 204, 51));
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeIcon.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(welcomeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeButton)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(welcomeText)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankLogo.png"))); // NOI18N

        withdrawPageButton.setBackground(new java.awt.Color(204, 0, 0));
        withdrawPageButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        withdrawPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/withdrawIcon.png"))); // NOI18N
        withdrawPageButton.setText("Withdraw");
        withdrawPageButton.setBorder(null);
        withdrawPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawPageButtonActionPerformed(evt);
            }
        });

        depositPageButton.setBackground(new java.awt.Color(0, 153, 0));
        depositPageButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        depositPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/depositIcon.png"))); // NOI18N
        depositPageButton.setText("Deposit");
        depositPageButton.setBorder(null);
        depositPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositPageButtonActionPerformed(evt);
            }
        });

        currentBalance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        currentBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentBalance.setText("Current Balance: $0");

        totalWithdraw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalWithdraw.setForeground(new java.awt.Color(204, 0, 0));
        totalWithdraw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalWithdraw.setText("Total Withdraw: ");

        totalBudget.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalBudget.setForeground(new java.awt.Color(0, 0, 0));
        totalBudget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalBudget.setText("Budget Remaining:");

        totalDeposit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalDeposit.setForeground(new java.awt.Color(0, 153, 51));
        totalDeposit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalDeposit.setText("Total Deposited: ");
        totalDeposit.setMaximumSize(new java.awt.Dimension(100, 20));
        totalDeposit.setMinimumSize(new java.awt.Dimension(100, 20));
        totalDeposit.setPreferredSize(new java.awt.Dimension(100, 20));

        newBudget.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newBudget.setText("Enter Budget");
        newBudget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newBudgetMouseClicked(evt);
            }
        });
        newBudget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newBudgetKeyTyped(evt);
            }
        });

        setBudget.setBackground(new java.awt.Color(204, 204, 204));
        setBudget.setForeground(new java.awt.Color(0, 0, 0));
        setBudget.setText("Set Budget");
        setBudget.setBorder(null);
        setBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBudgetActionPerformed(evt);
            }
        });
        setBudget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                setBudgetKeyTyped(evt);
            }
        });

        errorField.setForeground(new java.awt.Color(153, 0, 0));
        errorField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(depositPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(43, 43, 43)
                .addComponent(withdrawPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newBudget, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(setBudget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(283, 283, 283)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(totalBudget)))
                        .addGap(28, 28, 28)))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(withdrawPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(depositPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addComponent(currentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(totalDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(totalBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(newBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(errorField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawPageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawPageButtonActionPerformed

    private void depositPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositPageButtonActionPerformed
        new DepositPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_depositPageButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        new MainPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void setBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBudgetActionPerformed
        String stringedBudget = newBudget.getText();
        try {
            double newSetBudget = Double.parseDouble(stringedBudget);
        String[] response = Balance.setNewBudget(username, newSetBudget);
        if (response[0].equals("true")) {
            BalancePage balancePage = new BalancePage();

            // Make the WithdrawPage instance visible
            balancePage.setVisible(true);

            // Dispose of the current window
            dispose();
        } else {
            errorField.setText(response[1]);
        }
        } catch (NumberFormatException e) {
            errorField.setText("Enter Integers!");
        }
    }//GEN-LAST:event_setBudgetActionPerformed

    private void newBudgetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newBudgetKeyTyped

    }//GEN-LAST:event_newBudgetKeyTyped

    private void setBudgetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_setBudgetKeyTyped

    }//GEN-LAST:event_setBudgetKeyTyped

    private void newBudgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBudgetMouseClicked
        newBudget.setText("");
    }//GEN-LAST:event_newBudgetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalancePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalancePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalancePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalancePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalancePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentBalance;
    private javax.swing.JButton depositPageButton;
    private javax.swing.JLabel errorField;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField newBudget;
    private javax.swing.JButton setBudget;
    private javax.swing.JLabel totalBudget;
    private javax.swing.JLabel totalDeposit;
    private javax.swing.JLabel totalWithdraw;
    private javax.swing.JLabel welcomeText;
    private javax.swing.JButton withdrawPageButton;
    // End of variables declaration//GEN-END:variables
}
